# -*- coding: utf-8 -*-
"""Fine_tuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w7CxKG0vVmgp-cLi9MiPlRlL6w1nUgfZ
"""

!pip install openai

import os
from openai import OpenAI

"""Set the api key (from qroq)"""

openai_api_key = os.environ.get("OPENAI_API_KEY")
if not openai_api_key:
  raise ValueError("Set OPENAI_API_KEY as an environment variable before running this script.")
# Configure client for Groq API
client = OpenAI(api_key=openai_api_key, base_url="https://api.groq.com/openai/v1")
def prompt_based_query(user_query):
  response=client.chat.completions.create(
      model = "llama-3.1-8b-instant", # Changed to a currently supported Groq model
      messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": user_query}
      ],
      temperature=0.2
  )
  return response.choices[0].message.content
print(prompt_based_query("What is the capital of India?"))

"""Step 1 : Load document"""

!pip install langchain-community

# Install sentence-transformers for HuggingFaceEmbeddings
!pip install sentence-transformers

import os
from langchain_community.document_loaders import TextLoader

# Create a placeholder file if it doesn't exist
# You should replace this with your actual company data
file_path = '/content/customer_support_finetuning_dataset.csv'
if not os.path.exists(file_path):
    with open(file_path, 'w') as f:
        f.write("This is a placeholder for your company data. Please add relevant text here.\n")

loader = TextLoader(file_path)
documents = loader.load()

"""Step 2 create the embedding + vector DB"""

# import os
# from langchain_community.embeddings import OpenAIEmbeddings
# from langchain_community.vectorstores import FAISS

# # This cell is causing an AuthenticationError because OpenAIEmbeddings
# # cannot be used with a Groq API key for embedding generation.
# # Groq does not provide an embedding service.

# # Please use the HuggingFaceEmbeddings setup in cell `a2e40687` instead
# # for generating embeddings. You can remove or ignore this cell.

# # embeddings = OpenAIEmbeddings(openai_api_key=os.environ.get('OPENAI_API_KEY'))
# # vector_db=FAISS.from_documents(documents,embeddings)

# Install the new package for HuggingFaceEmbeddings
!pip install -U langchain-huggingface
# Install faiss-cpu for FAISS vector store
!pip install faiss-cpu

from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

# Initialize HuggingFaceEmbeddings
# You can choose different models from Hugging Face if you prefer, e.g., 'sentence-transformers/all-MiniLM-L6-v2'
# For a fast, small model, 'BAAI/bge-small-en-v1.5' is a good choice
# For a more powerful model, 'BAAI/bge-large-en-v1.5' can be used, but might be slower.
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

vector_db=FAISS.from_documents(documents,embeddings)

"""Step 3 : retrieval + generation"""

def rag_query(query):
  docs = vector_db.similarity_search(query,k=3)
  context = " ".join(doc.page_content for doc in docs)
  response = client.chat.completions.create(
      model = "llama-3.1-8b-instant", # Changed to a currently supported Groq model
      messages=[
        {"role": "system", "content": "use the use the provided context to answer" },
         {"role":"user","content": f"context:{context} \n\nQuestions:{query}"}
      ]
  )
  return response.choices[0].message.content

!pip install transformers datasets peft accelerate bitsandbytes

"""#RAG

Step 1 : load the model
"""

from transformers import AutoTokenizer, AutoModelForCausalLM , BitsAndBytesConfig
import bitsandbytes as bnb
model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
tokenizer = AutoTokenizer.from_pretrained(model_name)
#define the bitsandbytes config for 8 bit quantization
quantization_config = BitsAndBytesConfig(
    load_in_8bit=True)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=quantization_config,
    device_map="auto",
)

"""Quantization is the process of converting any bigger values to smaller values , the above code converts any bit number to 8 bit number

apply LoRA(PEFT)
"""

from peft import LoraConfig,get_peft_model,prepare_model_for_kbit_training

"""prepare model for kbit training"""

from peft import LoraConfig, prepare_model_for_kbit_training
model = prepare_model_for_kbit_training(model)
lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["q_proj","v_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
    )

"""Step 3 : dataset preparation"""

from datasets import Dataset
data = [
    {"text": "What is the capital of India?", "answer": "The capital of India is Delhi."},
    {"text": "What is the largest planet in our solar system?", "answer": "Jupiter is the largest planet in our solar system"}
]
dataset = Dataset.from_list(data)

"""Step 4 : tokenization"""

def tokenize_function(example):
  return tokenizer(example["text"],trucnated=True,padding="max_length")
tokenized_dataset = dataset.map(tokenize_function)

"""Step 5: Training"""

#step 5: Training
from transformers import Trainer , TrainingArguments
from peft import get_peft_model # Ensure get_peft_model is available

#add labels to the tokenized_dataset for causal language mdelling
def add_labels_to_dataset(examples):
  examples['labels']=examples['input_ids']
  return examples
tokenized_dataset=tokenized_dataset.map(add_labels_to_dataset,batched=True)

# Apply LoRA config to the model to make it trainable
model = get_peft_model(model, lora_config)

training_args=TrainingArguments(
    output_dir="./lora_model",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=4,
    num_train_epochs=2,
    logging_steps=10,
    save_steps=50
)
trainer=Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset
)
trainer.train()

"""Step 6 : inferences"""

#step 6: inferences
def generate_response(prompt):
  inputs=tokenizer(prompt,return_tensors="pt").to("cuda")
  outputs=model.generate(**inputs,max_new_tokens=100)
  return tokenizer.decode(outputs[0])

print(generate_response("what is ROI"))